config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'attend', to: 'attendances#create'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:new, :create, :show, :index]
  resources :attendances, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :user_event_maps, foreign_key: "attended_event_id"
  has_many :attendees, :through => :user_event_maps, source: "attending_user"

  scope :upcoming, -> {where("date > ?", Time.now)}
  scope :previous, -> {where("date < ?", Time.now)}

  def self.upcoming_events
    self.where("date > ?", Time.now)
  end

  def self.previous_events
    self.where("date < ?", Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: "creator_id"
  has_many :user_event_maps, foreign_key: "attending_user_id"
  has_many :attended_events, :through => :user_event_maps, source: "attended_event"

  def upcoming_events
    self.events.where("date > ?", Time.now)
  end

  def previous_events
    self.events.where("date < ?", Time.now)
  end
end

app/models/user_event_map.rb
class UserEventMap < ApplicationRecord
  belongs_to :attended_event, :class_name => "Event"
  belongs_to :attending_user, :class_name => "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @user = current_user
    if !@user.nil?
      @attendance = @user.user_event_maps.build(attendance_params)
      if @attendance.save
        redirect_to @user unless !@user
      else
        redirect_to 'events#index'
      end
    else
      redirect_to 'events#index'
    end
  end

  private

    def attendance_params
      params.require(:user_event_map).permit(:attended_event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end
  def create
    @user = current_user
    if !@user.nil?
      @event = @user.events.build(event_params)
      if @event.save
        redirect_to @event
      else
        render 'new'
      end
    else
      render 'new'
    end
  end
  def index
    @events = Event.all
  end
  def show
    @event = Event.find_by(id: params[:id])
    @attendance = UserEventMap.new
  end

  private

    def event_params
      params.require(:event).permit(:description, :location, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in(user)
      redirect_to user
    else
      render 'new'
    end
  end
  def destroy
    log_out
    render 'new'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
  def log_out
    session[:user_id] = nil
  end

  # Returns current user or nil
  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)
    else
      user = nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<h5><%= link_to "View party", event %></h5>
<p>Host: <%= link_to event.creator.name, event.creator %> | Location: <%= event.location %> | <%= event.date.in_time_zone("Mountain Time (US & Canada)").strftime("%B %e, %l:%M%P") %></p>
<%= event.description %><hr>

app/views/events/index.html.erb
<h1>UPCOMING EVENTS</h1>
<%= render Event.upcoming.all %>
<h1>PREVIOUS EVENTS</h1>
<%= render Event.previous.all %>

app/views/events/new.html.erb
<h1>CREATE EVENT</h1>
<%= form_for @event do |f| %>
	<%= f.label :location %>
	<%= f.text_field :location %>

	<%= f.hidden_field :date, :value => (Time.now + 5.minutes) %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.submit "Create an event!" %>
<% end %>

app/views/events/show.html.erb
<h1>SHOW EVENT</h1>
<p>Host: <%= @event.creator.name %> | Location: <%= @event.location %> | <%= @event.date.in_time_zone("Mountain Time (US & Canada)").strftime("%B %e, %l:%M%P") %></p>
<%= @event.description %><hr><br>
<%= form_for @attendance, url: attend_path do |f| %>
	<%= f.hidden_field :attended_event_id, :value => @event.id %>
	<%= f.submit "Attend event" %>
<% end %><br>
<p><%= render @event.attendees %></p>

app/views/layouts/_header.html.erb
<h2>HEADER</h2>
<% if (user_id = session[:user_id]) %>
	<% user = User.find_by(id: user_id) %>
	<p>Current user: <%= user.name %></p>
	<%= link_to "Log out", logout_path, method: "delete" %>
	<%= link_to "Create event", new_event_path %>
<% else %>
	<%= link_to "Log in", login_path %>
	<%= link_to "Sign up", new_user_path %>
<% end %>
<%= link_to "Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<h4><%= user.name %> will be attending</h4>

app/views/users/new.html.erb
<h1>CREATE A NEW USER</h1>
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit "Create a user!" %>
<% end %>

app/views/users/show.html.erb
<h1>USER PROFILE</h1>
<h3><%= @user.name %> is the host of the following events</h3><hr>
<%= render @user.events %>
<h3><%= @user.name %> will be attending the following events</h3><hr>
<%= render @user.upcoming_events %>
<h3><%= @user.name %> has attended the following events</h3><hr>
<%= render @user.previous_events %>